services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: python3 manage.py runserver 0.0.0.0:80
    container_name: teams_c
    volumes:
    - .:/app
    ports:
    - "9000:80"
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge